### ISSUE TITLE
Pumpjack and underground pipes are rotated in random(?) directions

### ISSUE THREAD

**Issue by amdepott** [joelverhagen/FactorioTools#6]
I noticed that this started happening on Space Age / 2.0 update, but it may have happened earlier.

For example, this is my import blueprint string:
`0eNqV1MtuwyAQBdB/mTWKbAPD41eqqHJSVNHG2PKjamTx7yWunS5C5OkSi3sEo4tnOF0m1/U+jGBn8Oc2DGBfZhj8e6gvt2+hbhxY6Kam+6jPnxAZ+PDmvsGW8cjAhdGP3v2mlsX1NUzNyfVpA3tIM+jaIQXacLMTIuVBMriCRXOQMbIHpCIgWK2IKvMIpyB6BxGU69wRnkckAVF3ROQRpJwEN0TlEUU5idgQzCOaMli+IrrII+Y/19FVHikLgiK2tuknQykpnUXcUyilFWZVzJOxlJTWSr6nkGqrNmWZbnrXfnRNivz9Hhh8uX5YIhIrI4yRolCIisf4A7NYXwc=`

The output is:
`0eJycmOmOmzAUhd/Fv4mEd8irVNEoi5XShkUkVB1FefeyZVLIAV/Pzyz38/H1Obbhzg6XxlV1VtzY9s6yY1lc2fbHnV2zc7G/dN8V+9yxLauavPq1P/5mj4hlxcn9ZVv+2EXMFbfslrmhqv/w+VE0+cHV7R+it+qIVeW1LSiLjt1BZMQ+2Va22FNWu+Pwk2oHubm8pd4fj+gNLAhgEfdgHQSWFLD5BlhRWjGA7RQcr4M1ASwHcDIFm3WwoShWPZjzILKlSBYDOZ6SxTo5oSwfH8gqSHMa0A0T5AweU9rRkwUP6gan5E8oiPa0g1MSaAdyWKM5JYKcQ7SvH6QQ6gFtwlT/F8OscptbuTnXZVOc3gfQsN8xgppQ6KwfCkEtGcqHDBqC0iQUOt8yoNQ0mCr9WkUcTLV+rYLTqRIuFtQqgqnzzQdRJZ2aopMDSlWh0PkODKXSczU2YHYsGwSl54rDs14gKD1X483EEpTSczXu45aglB4rgS8O6OJET5WUCIqUSnqoBqEiJigNyJSAVCg1IFPjiSsIWumhEgJSodZpqBbnreEN2fiK09GIqNh6ioVeKU58I9sV2amnWA6rksLLe0xrGBewmtM6xqFwJXzVQ5x4Aqulp1o/HY6KFa0Y6/aabDywJKz2umyshk5RRJvhlvlsNjoFF/ts1t2UljyqvTZLxgsZKva6LFmOlqaaDMZD+0z2XCzoMu1zGf96+EHVVJvBaGqvzcRKuPTLZrk7ZU2+cZd2362z46YqL4j2OqMLl51/Hsqm7l6c6CTS6Q49g8ehI/DXLXAyhOGIr5NAvnieDPMZ2MgIOEIaOgP7usm/DSEjo2CfdOAoY4b71wvTPsFZGBnap6+8zGeB15kH8s0CvjXMQofU95zE35zUrig2kxGhTUoW42D0rnu52D1yt7jXO8qI/XH1tUdoI1KVplrF1hjbniL/AAAA//8DAAZVzYE=`

But it doesn't make sense in game
![image](https://github.com/user-attachments/assets/812b7fe9-1d70-4d12-881d-ea7643f56612)

**Comment by joelverhagen** [comment]
Definitely seems like a bug. You can imagine what direction the pumps/pipes SHOULD be going. And they're not. Real surprising.

**Comment by amdepott** [comment]
I am guessing that something changed with blueprint strings in 2.0, since FBE also can't import strings anymore.

**Comment by joelverhagen** [comment]
I have fixed this bug. Please let me know if you run into any other problems.

**Comment by amdepott** [comment]
Thank you for your quick fix on this. Hope you're enjoying 2.0/SA

**Comment by amdepott** [comment]
@joelverhagen I've done some more digging and it looks like `direction` was possibly updated from [0-8] to [0-16], probably in conjunction with the new rails
